### ISSUE TITLE
"Could not load beatmap successfully!" message when loading any beatmap

### ISSUE THREAD

**Issue by WiseDragoon5374** [Flutterish/Hitokori#33]
Upon swapping to Hitokori from any other mode, I get this error (copied from logs):

```
2022-05-27 01:38:55 [error]: Could not load beatmap successfully!
2022-05-27 01:38:55 [error]: System.MissingFieldException: Field not found: 'osu.Game.Beatmaps.BeatmapStatistic.Name'.
2022-05-27 01:38:55 [error]: at osu.Game.Rulesets.Hitokori.Beatmaps.HitokoriBeatmap.GetStatistics()+MoveNext()
2022-05-27 01:38:55 [error]: at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
2022-05-27 01:38:55 [error]: at osu.Game.Screens.Select.BeatmapInfoWedge.WedgeInfoText.getRulesetInfoLabels()
```

This subsequently leads to a broken, half-loaded beatmap in its place. I can still play it, however it cuts off at certain points and resumes after 1-3 seconds.

osu!lazer version: 2022.523.0

**Comment by Flutterish** [comment]
should be fixed with 0.18.16
