### ISSUE TITLE
Gameset wont register in version  2024 625.2 and higher

### ISSUE THREAD

**Issue by dudasmarcus** [Flutterish/Hitokori#51]
Upon the new update the ruleset wont load properly anymore

2024-07-11 19:25:12 [verbose]: at osu.Game.Rulesets.RulesetStore.addRuleset(Assembly assembly)
2024-07-11 19:25:13 [error]: Could not load ruleset "hitokori". Please check for an update from the developer.
2024-07-11 19:25:13 [verbose]: Ruleset load failed: System.MissingMethodException: Method not found: 'Void osu.Game.Beatmaps.Beatmap`1.set_Breaks(System.Collections.Generic.List`1<osu.Game.Beatmaps.Timing.BreakPeriod>)'.
2024-07-11 19:25:13 [verbose]: at osu.Game.Rulesets.Hitokori.Beatmaps.HitokoriBeatmapConverter.GenerateBreaks(HitokoriBeatmap Beatmap)
2024-07-11 19:25:13 [verbose]: at osu.Game.Rulesets.Hitokori.Beatmaps.HitokoriBeatmapConverter.ConvertBeatmap(IBeatmap original, CancellationToken cancellationToken)
2024-07-11 19:25:13 [verbose]: at osu.Game.Beatmaps.BeatmapConverter`1.Convert(CancellationToken cancellationToken)
2024-07-11 19:25:13 [verbose]: at osu.Game.Rulesets.RealmRulesetStore.testRulesetCompatibility(RulesetInfo rulesetInfo)
2024-07-11 19:25:13 [verbose]: at osu.Game.Rulesets.RealmRulesetStore.<prepareDetachedRulesets>b__5_0(Realm realm)

**Comment by ghost** [comment]
I can try fix it
lemme try

EDIT: Issue is found, fixing it
I'll send it here once I'm done

**Comment by ghost** [comment]
Issue Fixed
Although it is able to run, it causes crash on my computer (which is now fixed in 2024.8.20, shout out peppy)
To Hitokori Devs, there IS the fixed source code
https://mega.nz/file/yBYSmBKB#b9wsKlgjI0voko7bBfJwrbxIWKAdFhhGwdKdLSYGfww

(DrawableHitokoriJudgement.cs and HitokoriBeatmapConverter.cs are changed)

**Comment by dudasmarcus** [comment]
2024.817.0-lazer broken once more. it is able to run, then it crashes immediately after loading the beatmap and the sprites

**Comment by ghost** [comment]
no way this is already fixed in the given link

okay sorry my bad
https://mega.nz/file/nRwAwTjK#svCTHdWjWKWQj0wI1xnF6T7RPGa560DW-AeEviSieLc

**Comment by dudasmarcus** [comment]
I fear not. It just loads, plays the beatmap for maybe 3 secs then crashes
every time... And it wont even give me any traceback of what happened

Dňa st 28. 8. 2024, 6:29 Necodev ***@***.***> napísal(a):

**Comment by ghost** [comment]
no no no use the new link and download it
I am sure it is the working version

**Comment by dudasmarcus** [comment]
It works! Im replying from gmail and i didnt seem the mega link on your
second to last message.

Imma close this once im on github

Dňa št 29. 8. 2024, 14:16 Necodev ***@***.***> napísal(a):
